### ISSUE TITLE
specifying i3 instead of gdm breaks install

### ISSUE THREAD

**Issue by Laeeth** [symmetryinvestments/zfs-on-root-installer#8]
fails at sed on gnome display manager

**Comment by hamishcoleman** [comment]
Fixed in 0d73420d15689184cd8fef9588c085cd5d849285

However, you will probably still have issues if you replace the "ubuntu-gnome-desktop" package with "i3" - the ubuntu-gnome-desktop meta package installs a Greeter and a bunch of desktop tools as well as the Window Manager.  It might be simpler to append "i3" in addition to the meta package.

The intent was that the system would be usable for basic things by non expert users after the install had finished - I'd be assuming that anyone using i3 is an expert user and thus could just install it after the base install was completed.

I did test at least one other meta package when I added that option - "ubuntu-mate-desktop", but it probably makes sense to document some of the useful values for that option.
